const pageTranslations = {
  es: {
    "nav.home": "Inicio",
    "nav.services": "Servicios",
    "nav.training": "Formaciones",
    "nav.vision": "Filosofía",
    "nav.about": "Sobre nosotros",
    "nav.contact": "Contacto",
    "nav.cta": "Primera cita sin compromiso",
    "search.button": "Buscar",
    "search.label": "Buscar en la web",
    "search.placeholder": "Buscar en la web",
    "search.hint": "Escriba una palabra para buscar.",
    "submenu.management": "Consultoría de gestión",
    "submenu.digital": "Formaciones",
    "submenu.coaching": "Coaching profesional",
    "submenu.modules": "Todos los módulos",
    "submenu.aiBasics": "Fundamentos de IA",
    "submenu.aiPractice": "IA en la práctica",
    "submenu.today": "Hoy",
    "submenu.reality": "Realidad",
    "submenu.vision": "Visión",
    "submenu.aboutGss": "Conocer GSS",
    "submenu.community": "Comunidad GSS",
    "internal.vision.eyebrow": "Hoy · Realidad · Visión",
    "internal.vision.title": "Orientación para una transformación sostenible.",
    "internal.vision.todayTitle": "Hoy",
    "internal.vision.todayText": "Complejidad, incertidumbre, procesos fragmentados y desafíos profesionales y empresariales. El monolito aparece como la primera señal de orden y dirección en un entorno todavía poco claro.",
    "internal.vision.realityTitle": "Realidad",
    "internal.vision.realityText": "Consultoría, estructura, formación, implementación, desarrollo de competencias e integración de IA en procesos reales. El monolito se sitúa en el centro de un espacio ordenado de transformación.",
    "internal.vision.futureTitle": "Visión",
    "internal.vision.futureText": "Empresas, equipos y personas están mejor estructurados, son más competentes digitalmente y avanzan estratégicamente. El monolito representa orientación y crecimiento nacido de la claridad y la estructura.",
    "internal.services.eyebrow": "Servicios",
    "internal.services.title": "Pensar con claridad. Trabajar de forma digital. Desarrollar de manera sostenible.",
    "internal.services.text": "GSS une estrategia, cualificación e implementación. Cada servicio se orienta a desafíos reales y a próximos pasos comprensibles.",
    "internal.services.managementTitle": "Consultoría de gestión",
    "internal.services.managementText": "Estructura, análisis, integración y evaluación estratégica.",
    "internal.services.digitalTitle": "Formaciones",
    "internal.services.digitalText": "Competencias prácticas de IA y digitalización para procesos reales.",
    "internal.services.trainingTitle": "Formación",
    "internal.services.trainingText": "Cursos prácticos, fundamentos comprensibles y transferencia.",
    "internal.services.coachingTitle": "Coaching profesional",
    "internal.services.coachingText": "Orientación y desarrollo en etapas de cambio profesional.",
    "internal.services.qualityTitle": "Desarrollo de calidad",
    "internal.services.qualityText": "Preparación de futuras ofertas educativas con orientación AZAV.",
    "internal.services.pathTitle": "Consultoría + formación + implementación",
    "internal.services.pathText": "Consultoría, formación e implementación como camino integrado.",
    "internal.training.eyebrow": "Formación",
    "internal.training.title": "Entender la IA. Aplicarla. Desarrollarla.",
    "internal.training.text": "Ocho módulos coordinados para personas, equipos y organizaciones que desean hacer útil la inteligencia artificial de forma concreta.",
    "module.1": "Fundamentos de IA explicados de forma comprensible.",
    "module.2": "Prompting para obtener resultados claros.",
    "module.3": "Usar la IA eficazmente en el trabajo diario de oficina.",
    "module.4": "Analizar y optimizar procesos.",
    "module.5": "Datos, privacidad y responsabilidad.",
    "module.6": "Herramientas de IA para personas emprendedoras.",
    "module.7": "Integrar IA en proyectos.",
    "module.8": "Implementación y transferencia sostenible.",
    "internal.about.eyebrow": "Sobre nosotros",
    "internal.about.title": "La competencia técnica se encuentra con una perspectiva intercultural.",
    "internal.about.text": "GSS nace de la experiencia internacional, el compromiso social y una mirada práctica sobre digitalización y desarrollo profesional.",
    "internal.about.subTitle": "Un camino con sustancia.",
    "internal.about.p1": "La fundadora estudió informática e ingeniería de sistemas en República Dominicana. Su experiencia profesional en aduanas, el compromiso social en Frankfurt, el reconocimiento de su título en Alemania en 2021 y la certificación IHK como mediadora lingüística en 2024 marcan GSS.",
    "internal.about.p2": "Junto con Klaus Schmidt se construye una empresa que une consultoría, formación e implementación de forma comprensible.",
    "internal.community.eyebrow": "Comunidad GSS",
    "internal.community.title": "Aprender juntos. Compartir experiencias. Avanzar.",
    "internal.community.text": "Este espacio está preparado para futuros eventos, impulsos e intercambio sobre IA, digitalización y desarrollo profesional.",
    "internal.contact.title": "Creemos claridad juntos.",
    "internal.contact.text": "Cuéntenos brevemente en qué punto se encuentra. Nos pondremos en contacto para una primera conversación sin compromiso.",
    "consultation.eyebrow": "Primera cita",
    "consultation.title": "Dé el primer paso sin compromiso.",
    "consultation.text": "En una primera cita breve aclaramos su situación, el objetivo y el siguiente paso más útil. No tiene que tener todo definido: para eso está esta conversación.",
    "form.name": "Nombre *",
    "form.email": "Correo electrónico *",
    "form.phone": "Número móvil *",
    "form.topic": "Tema *",
    "form.topic.ai": "Formaciones",
    "form.topic.coaching": "Coaching profesional",
    "form.topic.training": "Formaciones",
    "form.topic.management": "Consultoría de gestión",
    "form.topic.digitalProducts": "Productos digitales",
    "form.topic.other": "Otro",
    "form.topicOther": "Escriba el tema *",
    "form.phonePlaceholder": "Solo número móvil",
    "form.preferredDate": "Fecha preferida según disponibilidad",
    "form.requesterType": "Situación *",
    "form.requester.private": "Persona privada",
    "form.requester.company": "Empresa",
    "form.requester.selfEmployed": "Autónomo/a",
    "form.requester.founder": "Fundación / start-up",
    "form.requester.institution": "Institución / centro educativo",
    "form.funding": "Financiación / ayuda",
    "form.funding.unknown": "Todavía no lo sé",
    "form.funding.interested": "Quiero revisar posibilidades de financiación",
    "form.funding.burgergeld": "Percibo Bürgergeld / busco ayuda",
    "form.funding.voucher": "Tengo bono / entidad financiadora",
    "form.funding.selfFunded": "Pago privado / paga la empresa",
    "form.message": "Mensaje",
    "form.submit": "Enviar consulta",
    "form.consultationToggle": "Primera cita sin compromiso",
    "form.whatsapp": "Contactar por WhatsApp",
    "footer.home": "Ir al inicio",
    "footer.navigation": "Navegación",
    "footer.social": "Redes sociales",
    "footer.community": "Comunidad GSS",
    "footer.events": "Eventos",
    "footer.blog": "Blog","footer.faq": "Preguntas frecuentes",
    "legal.aiActLink": "EU AI Act",
    "legal.aiActEyebrow": "Inteligencia artificial",
    "legal.aiActTitle": "EU AI Act",
    "legal.aiActNote": "Nota: esta información ofrece una orientación comprensible y no sustituye asesoramiento jurídico individual.",
    "legal.aiActWhatTitle": "1. De qué trata",
    "legal.aiActWhatText": "El EU AI Act es el marco jurídico europeo para la inteligencia artificial. Funciona con un enfoque basado en el riesgo: cuanto más pueda un sistema de IA afectar derechos, seguridad o áreas importantes de la vida, mayores serán los requisitos.",
    "legal.aiActGssTitle": "2. Qué significa para GSS",
    "legal.aiActGssText": "GSS utiliza y explica la IA como herramienta para consultoría, formación, organización y procesos digitales. Los sistemas de IA deben usarse de forma transparente, controlada y comprensible. Las decisiones con efectos jurídicos o relevantes no deben automatizarse sin control humano.",
    "legal.aiActLiteracyTitle": "3. Competencia en IA y transparencia",
    "legal.aiActLiteracyText": "Un punto importante es la competencia en IA: las personas que trabajan con IA deben comprender oportunidades, límites y riesgos. Por eso GSS considera formación, uso responsable, privacidad y control humano claro.",
    "legal.aiActTimelineTitle": "4. Contexto temporal",
    "legal.aiActTimelineText": "El AI Act está en vigor desde el 1 de agosto de 2024. Las prohibiciones de determinadas prácticas de IA y las obligaciones de competencia en IA se aplican desde el 2 de febrero de 2025. Otras obligaciones, por ejemplo para modelos de IA de propósito general y sistemas de alto riesgo, se aplican de forma gradual.",
    "legal.aiActContactTitle": "5. Preguntas sobre sistemas de IA",
    "legal.aiActContactText": "Si GSS incorpora más adelante herramientas de IA, automatizaciones CRM, agentes de voz o chatbots en uso productivo, deberán documentarse de forma transparente finalidad, tratamiento de datos, proveedor, control humano y clasificación legal.",
    "faq.eyebrow": "FAQ",
    "faq.title": "Preguntas y respuestas",
    "faq.text": "Aquí encuentra respuestas breves sobre GSS, contacto, formación, privacidad, IA y próximos pasos.",
    "faq.q1": "¿Qué hace GSS Management Consulting?",
    "faq.a1": "GSS conecta consultoría de gestión, formaciones, coaching profesional y herramientas digitales. El objetivo es ayudar a personas y organizaciones a trabajar con más claridad, estructura y competencia digital.",
    "faq.q2": "¿Para quién son las ofertas?",
    "faq.a2": "Las ofertas están pensadas para empresas, autónomos, personas emprendedoras, instituciones y personas en cambio profesional.",
    "faq.q3": "¿Cómo funciona una primera consulta?",
    "faq.a3": "Usted envía los datos principales mediante el formulario. Después GSS puede valorar la necesidad y preparar una primera respuesta o una cita sin compromiso.",
    "faq.q4": "¿Qué significa primera cita sin compromiso?",
    "faq.a4": "Es una primera orientación sin obligación. Se aclaran la situación, el objetivo y posibles próximos pasos sin crear un compromiso directo.",
    "faq.q5": "¿Qué papel tiene la IA en GSS?",
    "faq.a5": "La IA se entiende como herramienta para orientación, estructura, automatización y formación. Siguen siendo importantes la transparencia, la privacidad y el control humano.",
    "faq.q6": "¿Mis datos se envían directamente a un CRM?",
    "faq.a6": "La web está preparada técnicamente para una futura conexión CRM. Mientras no exista un endpoint CRM conectado, los datos no se envían a un CRM externo.",
    "faq.q7": "¿Qué ocurre con WhatsApp?",
    "faq.a7": "El contacto por WhatsApp está preparado. Antes del uso productivo deben configurarse número, información de privacidad, consentimiento y proceso CRM.",
    "faq.q8": "¿Los textos legales son finales?",
    "faq.a8": "No. Son una estructura profesional de base. Antes de publicar, Impressum, privacidad, cookies y EU AI Act deben revisarse con los datos reales de la empresa.",
    "faq.q9": "¿Qué significa el EU AI Act para GSS?",
    "faq.a9": "GSS debería usar la IA de forma transparente, fomentar competencia en IA, revisar riesgos y documentar qué herramientas se usan y para qué finalidad.","legal.footerTitle": "Legal",
    "legal.privacyLink": "Protección de datos",
    "legal.imprintLink": "Aviso legal",
    "legal.cookiesLink": "Cookies",
    "legal.pageTitle": "Aviso legal",
    "legal.updatedShort": "Última actualización: junio de 2026",
    "legal.pageText": "Aquí encuentra privacidad, cookies y aviso legal de GSS Management Consulting en un lugar central.",
    "legal.privacyEyebrow": "Legal",
    "legal.privacyTitle": "Política de privacidad",
    "legal.updated": "Actualizado: junio de 2026. Esta plantilla no sustituye asesoramiento jurídico individual y debe revisarse con los datos finales de la empresa antes de su publicación.",
    "legal.controllerTitle": "1. Responsable del tratamiento",
    "legal.controllerText": "La entidad responsable del tratamiento de datos en este sitio web es GSS Management Consulting, [añadir nombre de la titular / persona representante], [añadir calle y número], [añadir código postal y ciudad], Alemania. Email: [añadir email]. Teléfono: [añadir teléfono].",
    "legal.dataTitle": "2. Datos que se tratan",
    "legal.dataText": "Al visitar el sitio web pueden tratarse datos técnicos necesarios, por ejemplo dirección IP, fecha y hora de acceso, tipo de navegador, sistema operativo, páginas visitadas y registros del servidor. Si utiliza el formulario de contacto, el chat o posteriormente WhatsApp, tratamos los datos que introduzca, como nombre, email, teléfono, asunto y mensaje.",
    "legal.purposeTitle": "3. Finalidades y bases jurídicas",
    "legal.purposeText": "El tratamiento se realiza para ofrecer y proteger el sitio web, responder solicitudes de contacto, preparar una primera consulta, comunicarse con personas interesadas y mejorar los contenidos. Las bases jurídicas pueden ser el art. 6.1 b RGPD para comunicación precontractual, el art. 6.1 f RGPD para intereses legítimos en seguridad y comunicación, y el art. 6.1 a RGPD cuando sea necesario el consentimiento.",
    "legal.cookiesTitle": "4. Cookies, contenidos externos y asistente de IA",
    "legal.cookiesText": "Este sitio debería usar sin consentimiento solo cookies técnicamente necesarias. Para cookies no necesarias, análisis, marketing, medios integrados o tecnologías similares se requiere una autorización previa, libre, informada y revocable. Si se conectan herramientas de análisis, videos, mapas, WhatsApp, CRM, calendario o un servicio externo de IA, deberán añadirse proveedor, finalidad, base jurídica, duración, categorías de datos, transferencia internacional y mecanismo de consentimiento.",
    "legal.securityTitle": "5. Seguridad técnica y HTTPS/SSL",
    "legal.securityText": "HTTPS/SSL es una medida técnica para proteger la transmisión cifrada entre navegador y sitio web. No sustituye la política de privacidad ni una revisión RGPD/DSGVO, pero puede describirse dentro de las medidas técnicas y organizativas adecuadas.",
    "legal.retentionTitle": "6. Conservación y transferencia",
    "legal.retentionText": "Los datos personales se conservan solo durante el tiempo necesario para la finalidad correspondiente o mientras existan obligaciones legales de conservación. Solo se compartirán cuando sea necesario para tramitar la solicitud, exista obligación legal, haya consentimiento o se usen proveedores fiables bajo encargo de tratamiento.",
    "legal.rightsTitle": "7. Sus derechos",
    "legal.rightsText": "Conforme al RGPD, usted tiene especialmente derechos de acceso, rectificación, supresión, limitación del tratamiento, portabilidad y oposición. Puede retirar su consentimiento en cualquier momento con efecto futuro. También tiene derecho a presentar una reclamación ante una autoridad de protección de datos competente.",
    "legal.imprintEyebrow": "Identificación del proveedor",
    "legal.imprintTitle": "Aviso legal",
    "legal.providerTitle": "Información según § 5 DDG",
    "legal.providerText": "GSS Management Consulting<br>[añadir nombre de la titular / forma jurídica]<br>[añadir calle y número]<br>[añadir código postal y ciudad]<br>Alemania",
    "legal.contactTitle": "Contacto",
    "legal.contactLegalText": "Teléfono: [añadir teléfono]<br>Email: [añadir email]<br>Sitio web: [añadir dominio]",
    "legal.representedTitle": "Representación",
    "legal.representedText": "[Añadir persona representante / dirección]",
    "legal.taxTitle": "IVA / datos registrales",
    "legal.taxText": "Número de identificación fiscal a efectos de IVA según § 27a UStG: [añadir si existe]. Registro y número registral: [añadir si existe]. Si no hay inscripción registral o ID de IVA, adaptar esta sección.",
    "legal.liabilityTitle": "Responsabilidad por contenidos y enlaces",
    "legal.liabilityText": "Los contenidos de este sitio web se han creado con cuidado. No obstante, no se puede garantizar su exactitud, integridad o actualidad. Los enlaces externos conducen a contenidos de terceros; el proveedor correspondiente es responsable de dichos contenidos.",
    "legal.disputeTitle": "Resolución de litigios de consumo",
    "legal.disputeText": "No estamos obligados ni dispuestos a participar en procedimientos de resolución de litigios ante una junta de arbitraje de consumo, salvo obligación legal.",
    "legal.cookiesEyebrow": "Cookies",
    "legal.cookiesPageTitle": "Cookies y consentimientos",
    "legal.cookiesNecessaryTitle": "1. Cookies técnicamente necesarias",
    "legal.cookiesNecessaryText": "Este sitio debería utilizar solo cookies necesarias para funcionamiento, seguridad y funciones básicas. Normalmente pueden basarse en intereses legítimos o necesidad técnica.",
    "legal.cookiesConsentTitle": "2. Servicios que requieren consentimiento",
    "legal.cookiesConsentText": "Analítica, marketing, medios integrados, calendarios externos, integraciones CRM, seguimiento de WhatsApp o servicios de IA solo deben activarse tras un consentimiento libre e informado, salvo que sean técnicamente necesarios.",
    "legal.cookiesManageTitle": "3. Gestión y retirada",
    "legal.cookiesManageText": "Cuando se integre un banner o herramienta de consentimiento, debe existir una forma sencilla de aceptar, rechazar y retirar consentimientos más adelante."
    ,"detail.cta": "Solicitar primera consulta",
    "detail.back": "Ver todos los servicios",
    "detail.processEyebrow": "Proceso",
    "detail.processTitle": "De la necesidad a la implementación",
    "detail.step1Title": "Análisis",
    "detail.step1Text": "Se aclaran la situación inicial, los objetivos y los bloqueos.",
    "detail.step2Title": "Estructura",
    "detail.step2Text": "GSS desarrolla un plan comprensible con prioridades.",
    "detail.step3Title": "Transferencia",
    "detail.step3Text": "La implementación se prepara y acompaña de forma práctica.",
    "detail.management.eyebrow": "Servicio GSS",
    "detail.management.title": "Consultoría de gestión",
    "detail.management.text": "Estructura, análisis y orientación estratégica para tomar mejores decisiones y avanzar con claridad.",
    "detail.management.benefitsTitle": "Lo que recibe",
    "detail.management.benefitsText": "Acompañamiento estructurado para ordenar procesos, prioridades y próximos pasos.",
    "detail.management.card1Title": "Orientación estratégica",
    "detail.management.card1Text": "Análisis de estructuras, procesos y vías de decisión.",
    "detail.management.card2Title": "Claridad de procesos",
    "detail.management.card2Text": "Los procesos complejos se ordenan y priorizan de forma comprensible.",
    "detail.management.card3Title": "Roadmap aplicable",
    "detail.management.card3Text": "Próximos pasos concretos para organización, digitalización y desarrollo.",
    "detail.management.card4Title": "Evaluación",
    "detail.management.card4Text": "Los resultados se revisan, ajustan y consolidan de forma sostenible.",
    "detail.training.eyebrow": "Servicio GSS",
    "detail.training.title": "Formaciones",
    "detail.training.text": "Formaciones prácticas en IA, herramientas digitales y transferencia para el trabajo real.",
    "detail.training.benefitsTitle": "Lo que aprende",
    "detail.training.benefitsText": "Competencias aplicables para usar IA y digitalización con criterio.",
    "detail.training.card1Title": "Fundamentos de IA",
    "detail.training.card1Text": "Entrada comprensible a conceptos, oportunidades, riesgos y aplicación.",
    "detail.training.card2Title": "Prompting y herramientas",
    "detail.training.card2Text": "Ejercicios prácticos para obtener mejores resultados con sistemas de IA.",
    "detail.training.card3Title": "IA en el trabajo diario",
    "detail.training.card3Text": "Casos de uso para oficina, proyectos, emprendimiento y organización.",
    "detail.training.card4Title": "Transferencia",
    "detail.training.card4Text": "Los contenidos se traducen en rutinas concretas de trabajo.",
    "detail.coaching.eyebrow": "Servicio GSS",
    "detail.coaching.title": "Coaching profesional",
    "detail.coaching.text": "Orientación para etapas de cambio profesional, posicionamiento y desarrollo de competencias.",
    "detail.coaching.benefitsTitle": "Cómo le acompaña GSS",
    "detail.coaching.benefitsText": "Claridad personal, estructura profesional y herramientas digitales para avanzar.",
    "detail.coaching.card1Title": "Orientación",
    "detail.coaching.card1Text": "Clarificación de situación profesional, fortalezas y próximas opciones.",
    "detail.coaching.card2Title": "Perfil de competencias",
    "detail.coaching.card2Text": "Visibilización de capacidades, experiencia y áreas de desarrollo.",
    "detail.coaching.card3Title": "Solicitud y posicionamiento",
    "detail.coaching.card3Text": "Apoyo para perfil, comunicación y decisiones profesionales.",
    "detail.coaching.card4Title": "Competencia digital",
    "detail.coaching.card4Text": "IA y herramientas digitales como apoyo útil en el camino profesional."
  },
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.training": "Training",
    "nav.vision": "Philosophy",
    "nav.about": "About us",
    "nav.contact": "Contact",
    "nav.cta": "Initial appointment, no obligation",
    "search.button": "Search",
    "search.label": "Search the website",
    "search.placeholder": "Search the website",
    "search.hint": "Enter a search term.",
    "submenu.management": "Management consulting",
    "submenu.digital": "Training",
    "submenu.coaching": "Career coaching",
    "submenu.modules": "All modules",
    "submenu.aiBasics": "AI fundamentals",
    "submenu.aiPractice": "AI in practice",
    "submenu.today": "Today",
    "submenu.reality": "Reality",
    "submenu.vision": "Vision",
    "submenu.aboutGss": "Get to know GSS",
    "submenu.community": "GSS Community",
    "internal.vision.eyebrow": "Today · Reality · Vision",
    "internal.vision.title": "Orientation for sustainable transformation.",
    "internal.vision.todayTitle": "Today",
    "internal.vision.todayText": "Complexity, uncertainty, fragmented processes and professional or business challenges. The monolith appears as the first sign of order and direction in an environment that is not yet clear.",
    "internal.vision.realityTitle": "Reality",
    "internal.vision.realityText": "Consulting, structure, training, implementation, competence development and AI integration in real workflows. The monolith stands visibly at the center of an ordered transformation space.",
    "internal.vision.futureTitle": "Vision",
    "internal.vision.futureText": "Companies, teams and individuals become clearer, more digitally competent and strategically developed. The monolith represents orientation and growth that comes from clarity and structure.",
    "internal.services.eyebrow": "Services",
    "internal.services.title": "Think clearly. Work digitally. Develop sustainably.",
    "internal.services.text": "GSS connects strategy, qualification and implementation. Every service is focused on real challenges and understandable next steps.",
    "internal.services.managementTitle": "Management consulting",
    "internal.services.managementText": "Structure, analysis, integration and strategic evaluation.",
    "internal.services.digitalTitle": "Training",
    "internal.services.digitalText": "Practical AI and digitalization skills for real workflows.",
    "internal.services.trainingTitle": "Training",
    "internal.services.trainingText": "Practical courses, clear foundations and transfer.",
    "internal.services.coachingTitle": "Career coaching",
    "internal.services.coachingText": "Orientation and development during professional change.",
    "internal.services.qualityTitle": "Quality development",
    "internal.services.qualityText": "AZAV-oriented preparation for future educational services.",
    "internal.services.pathTitle": "Consulting + training + implementation",
    "internal.services.pathText": "Consulting, training and implementation as an integrated path.",
    "internal.training.eyebrow": "Training",
    "internal.training.title": "Understand AI. Apply it. Develop further.",
    "internal.training.text": "Eight coordinated modules for people, teams and organizations that want to make artificial intelligence practically useful.",
    "module.1": "AI fundamentals explained clearly.",
    "module.2": "Prompting for clear results.",
    "module.3": "Using AI effectively in everyday office work.",
    "module.4": "Analyze and optimize processes.",
    "module.5": "Data, privacy and responsibility.",
    "module.6": "AI tools for founders.",
    "module.7": "Integrate AI into projects.",
    "module.8": "Implementation and sustainable transfer.",
    "internal.about.eyebrow": "About us",
    "internal.about.title": "Technical expertise meets an intercultural perspective.",
    "internal.about.text": "GSS grows from international experience, social engagement and a consistently practical view of digitalization and professional development.",
    "internal.about.subTitle": "A path with substance.",
    "internal.about.p1": "The founder studied computer science and systems engineering in the Dominican Republic. Professional experience in customs, social engagement in Frankfurt, recognition of her degree in Germany in 2021 and the IHK language mediator exam in 2024 shape GSS.",
    "internal.about.p2": "Together with Klaus Schmidt, she is building a company that connects consulting, training and implementation in an understandable way.",
    "internal.community.eyebrow": "GSS Community",
    "internal.community.title": "Learn together. Share experience. Move forward.",
    "internal.community.text": "This area is prepared for future events, impulses and exchange around AI, digitalization and professional development.",
    "internal.contact.title": "Let us create clarity together.",
    "internal.contact.text": "Tell us briefly where you are today. We will contact you for a non-binding initial conversation.",
    "consultation.eyebrow": "Initial appointment",
    "consultation.title": "Take the first step with no obligation.",
    "consultation.text": "In a short initial appointment, we clarify your situation, your goal and the most useful next step. You do not need to have everything figured out: that is exactly what this conversation is for.",
    "form.name": "Name *",
    "form.email": "Email *",
    "form.phone": "Mobile number *",
    "form.topic": "Topic *",
    "form.topic.ai": "Training",
    "form.topic.coaching": "Career coaching",
    "form.topic.training": "Training",
    "form.topic.management": "Management consulting",
    "form.topic.digitalProducts": "Digital products",
    "form.topic.other": "Other",
    "form.topicOther": "Write the topic *",
    "form.phonePlaceholder": "Mobile number only",
    "form.preferredDate": "Preferred date, subject to availability",
    "form.requesterType": "Situation *",
    "form.requester.private": "Private individual",
    "form.requester.company": "Company",
    "form.requester.selfEmployed": "Self-employed",
    "form.requester.founder": "Founder / start-up",
    "form.requester.institution": "Institution / education provider",
    "form.funding": "Funding / support",
    "form.funding.unknown": "Not clear yet",
    "form.funding.interested": "I want to check funding options",
    "form.funding.burgergeld": "I receive Bürgergeld / seek support",
    "form.funding.voucher": "Voucher / funding body available",
    "form.funding.selfFunded": "Self-funded / company pays",
    "form.message": "Message",
    "form.submit": "Send request",
    "form.consultationToggle": "Initial appointment, no obligation",
    "form.whatsapp": "Contact via WhatsApp",
    "footer.home": "Back to home",
    "footer.navigation": "Navigation",
    "footer.social": "Social Media",
    "footer.community": "GSS Community",
    "footer.events": "Events",
    "footer.blog": "Blog","footer.faq": "FAQ",
    "legal.aiActLink": "EU AI Act",
    "legal.aiActEyebrow": "Artificial intelligence",
    "legal.aiActTitle": "EU AI Act",
    "legal.aiActNote": "Note: this information provides understandable orientation and does not replace individual legal advice.",
    "legal.aiActWhatTitle": "1. What it is about",
    "legal.aiActWhatText": "The EU AI Act is the European legal framework for artificial intelligence. It follows a risk-based approach: the more an AI system may affect rights, safety or important areas of life, the higher the requirements.",
    "legal.aiActGssTitle": "2. What it means for GSS",
    "legal.aiActGssText": "GSS uses and explains AI as a tool for consulting, training, organisation and digital workflows. AI systems should be used transparently, under control and in a traceable way. Decisions with legal or significant effects should not be blindly automated.",
    "legal.aiActLiteracyTitle": "3. AI literacy and transparency",
    "legal.aiActLiteracyText": "AI literacy is an important point: people working with AI should understand opportunities, limits and risks. GSS therefore considers education, responsible use, privacy and clear human control.",
    "legal.aiActTimelineTitle": "4. Timeline context",
    "legal.aiActTimelineText": "The AI Act has been in force since 1 August 2024. Prohibitions of certain AI practices and AI literacy obligations have applied since 2 February 2025. Further obligations, for example for general-purpose AI models and high-risk systems, apply gradually.",
    "legal.aiActContactTitle": "5. Questions about AI systems",
    "legal.aiActContactText": "If GSS later uses concrete AI tools, CRM automations, voice agents or chatbots in production, purpose, data processing, provider, human control and legal classification should be documented transparently.",
    "faq.eyebrow": "FAQ",
    "faq.title": "Questions and answers",
    "faq.text": "Here you will find short answers about GSS, contact, training, privacy, AI and next steps.",
    "faq.q1": "What does GSS Management Consulting do?",
    "faq.a1": "GSS connects management consulting, training, career coaching and digital tools. The goal is to help people and organisations work with more clarity, structure and digital competence.",
    "faq.q2": "Who are the offers for?",
    "faq.a2": "The offers are designed for companies, self-employed professionals, founders, institutions and people in career transition.",
    "faq.q3": "How does a first request work?",
    "faq.a3": "You send the most important details through the contact form. GSS can then assess the need and prepare an initial response or a non-binding appointment.",
    "faq.q4": "What does initial appointment with no obligation mean?",
    "faq.a4": "It is a first orientation without obligation. The situation, goal and possible next steps are clarified without creating a direct commitment.",
    "faq.q5": "What role does AI play at GSS?",
    "faq.a5": "AI is understood as a tool for orientation, structure, automation and training. Transparency, privacy and human control remain important.",
    "faq.q6": "Are my data sent directly to a CRM?",
    "faq.a6": "The website is technically prepared for a future CRM connection. As long as no CRM endpoint is connected, the data are not sent to an external CRM.",
    "faq.q7": "What happens with WhatsApp?",
    "faq.a7": "WhatsApp contact is prepared. Before productive use, number, privacy information, consent and CRM process should be finalised.",
    "faq.q8": "Are the legal texts final?",
    "faq.a8": "No. They are a professional base structure. Before publication, imprint, privacy, cookies and EU AI Act sections should be reviewed with the real company data.",
    "faq.q9": "What does the EU AI Act mean for GSS?",
    "faq.a9": "GSS should use AI transparently, promote AI literacy, review risks and document which tools are used and for what purpose.","legal.footerTitle": "Legal",
    "legal.privacyLink": "Privacy policy",
    "legal.imprintLink": "Imprint",
    "legal.cookiesLink": "Cookies",
    "legal.pageTitle": "Legal notice",
    "legal.updatedShort": "Last updated: June 2026",
    "legal.pageText": "Here you can find privacy, cookies and provider information for GSS Management Consulting in one central place.",
    "legal.privacyEyebrow": "Legal",
    "legal.privacyTitle": "Privacy policy",
    "legal.updated": "Last updated: June 2026. This template does not replace individual legal advice and should be reviewed with the final company data before publication.",
    "legal.controllerTitle": "1. Controller",
    "legal.controllerText": "The controller responsible for data processing on this website is GSS Management Consulting, [add owner / authorised representative], [add street and number], [add postcode and city], Germany. Email: [add email address]. Phone: [add phone number].",
    "legal.dataTitle": "2. Data processed",
    "legal.dataText": "When visiting the website, technically necessary access data may be processed, for example IP address, date and time of access, browser type, operating system, pages visited and server log data. If you use the contact form, chat or later WhatsApp, we process the information you provide, such as name, email address, phone number, subject and message.",
    "legal.purposeTitle": "3. Purposes and legal bases",
    "legal.purposeText": "Processing takes place to provide and secure the website, handle contact requests, prepare an initial consultation, communicate with interested persons and improve the content offered. Legal bases may include Art. 6(1)(b) GDPR for pre-contractual communication, Art. 6(1)(f) GDPR for legitimate interests in security and communication, and Art. 6(1)(a) GDPR where consent is required.",
    "legal.cookiesTitle": "4. Cookies, external content and AI assistant",
    "legal.cookiesText": "This website should only set technically necessary cookies without consent. Non-essential cookies, analytics, marketing, embedded media or similar technologies require prior, freely given, informed and revocable consent. If analytics tools, videos, maps, WhatsApp, a CRM, a calendar or an external AI service are connected later, provider, purpose, legal basis, retention period, data categories, international transfer and consent mechanism must be added accordingly.",
    "legal.securityTitle": "5. Technical security and HTTPS/SSL",
    "legal.securityText": "HTTPS/SSL is a technical measure for encrypted transmission between browser and website. It does not replace a privacy policy or GDPR review, but it can be described as part of appropriate technical and organisational measures.",
    "legal.retentionTitle": "6. Retention and disclosure",
    "legal.retentionText": "Personal data is stored only as long as required for the respective purpose or as long as statutory retention obligations apply. Disclosure takes place only if necessary to process the request, if there is a legal obligation, if consent has been given or if reliable service providers are used under a data processing agreement.",
    "legal.rightsTitle": "7. Your rights",
    "legal.rightsText": "Under the GDPR, you have in particular rights of access, rectification, erasure, restriction of processing, data portability and objection. You may withdraw consent at any time with effect for the future. You also have the right to lodge a complaint with a competent data protection supervisory authority.",
    "legal.imprintEyebrow": "Provider identification",
    "legal.imprintTitle": "Imprint",
    "legal.providerTitle": "Information pursuant to § 5 DDG",
    "legal.providerText": "GSS Management Consulting<br>[add owner / legal form]<br>[add street and number]<br>[add postcode and city]<br>Germany",
    "legal.contactTitle": "Contact",
    "legal.contactLegalText": "Phone: [add phone number]<br>Email: [add email address]<br>Website: [add domain]",
    "legal.representedTitle": "Represented by",
    "legal.representedText": "[Add authorised representative / management]",
    "legal.taxTitle": "VAT / register information",
    "legal.taxText": "VAT identification number pursuant to § 27a UStG: [add if available]. Register court and registration number: [add if available]. If there is no register entry or VAT ID, adapt this section accordingly.",
    "legal.liabilityTitle": "Liability for content and links",
    "legal.liabilityText": "The content of this website has been created with care. Nevertheless, no guarantee can be given for accuracy, completeness or timeliness. External links lead to third-party content; the respective provider is responsible for such content.",
    "legal.disputeTitle": "Consumer dispute resolution",
    "legal.disputeText": "We are not obliged and not willing to participate in dispute resolution proceedings before a consumer arbitration board unless there is a legal obligation.",
    "legal.cookiesEyebrow": "Cookies",
    "legal.cookiesPageTitle": "Cookies and consent",
    "legal.cookiesNecessaryTitle": "1. Technically necessary cookies",
    "legal.cookiesNecessaryText": "This website should only use cookies required for operation, security and basic functions. These can generally be based on legitimate interests or technical necessity.",
    "legal.cookiesConsentTitle": "2. Services requiring consent",
    "legal.cookiesConsentText": "Analytics, marketing, embedded media, external calendars, CRM integrations, WhatsApp tracking or AI services should only be activated after freely given and informed consent, unless technically necessary.",
    "legal.cookiesManageTitle": "3. Management and withdrawal",
    "legal.cookiesManageText": "Once a cookie banner or consent tool is integrated, there must be a simple way to accept, reject and later withdraw consent."
    ,"detail.cta": "Request initial consultation",
    "detail.back": "View all services",
    "detail.processEyebrow": "Process",
    "detail.processTitle": "From need to implementation",
    "detail.step1Title": "Analysis",
    "detail.step1Text": "The current situation, goals and bottlenecks are clarified.",
    "detail.step2Title": "Structure",
    "detail.step2Text": "GSS develops an understandable plan with priorities.",
    "detail.step3Title": "Transfer",
    "detail.step3Text": "Implementation is prepared and supported in a practical way.",
    "detail.management.eyebrow": "GSS service",
    "detail.management.title": "Management consulting",
    "detail.management.text": "Structure, analysis and strategic orientation for better decisions and clearer progress.",
    "detail.management.benefitsTitle": "What you receive",
    "detail.management.benefitsText": "Structured support to clarify processes, priorities and next steps.",
    "detail.management.card1Title": "Strategic orientation",
    "detail.management.card1Text": "Analysis of structures, processes and decision paths.",
    "detail.management.card2Title": "Process clarity",
    "detail.management.card2Text": "Complex workflows are organized and prioritized in an understandable way.",
    "detail.management.card3Title": "Actionable roadmap",
    "detail.management.card3Text": "Concrete next steps for organization, digitalization and development.",
    "detail.management.card4Title": "Evaluation",
    "detail.management.card4Text": "Results are reviewed, adjusted and sustainably anchored.",
    "detail.training.eyebrow": "GSS service",
    "detail.training.title": "Training",
    "detail.training.text": "Practical training in AI, digital tools and transfer for real work.",
    "detail.training.benefitsTitle": "What you learn",
    "detail.training.benefitsText": "Applicable skills to use AI and digitalization with good judgment.",
    "detail.training.card1Title": "AI foundations",
    "detail.training.card1Text": "Clear introduction to concepts, opportunities, risks and application.",
    "detail.training.card2Title": "Prompting and tools",
    "detail.training.card2Text": "Practical exercises for better results with AI systems.",
    "detail.training.card3Title": "AI in everyday work",
    "detail.training.card3Text": "Use cases for office work, projects, entrepreneurship and organization.",
    "detail.training.card4Title": "Transfer",
    "detail.training.card4Text": "Learning content is translated into concrete working routines.",
    "detail.coaching.eyebrow": "GSS service",
    "detail.coaching.title": "Career coaching",
    "detail.coaching.text": "Orientation for career transition, positioning and competence development.",
    "detail.coaching.benefitsTitle": "How GSS supports you",
    "detail.coaching.benefitsText": "Personal clarity, professional structure and digital tools for progress.",
    "detail.coaching.card1Title": "Orientation",
    "detail.coaching.card1Text": "Clarification of career situation, strengths and next options.",
    "detail.coaching.card2Title": "Competence profile",
    "detail.coaching.card2Text": "Making skills, experience and development areas visible.",
    "detail.coaching.card3Title": "Application and positioning",
    "detail.coaching.card3Text": "Support for profile, communication and professional decisions.",
    "detail.coaching.card4Title": "Digital competence",
    "detail.coaching.card4Text": "AI and digital tools become useful support on the professional path."
  }
};

const originalText = Object.fromEntries(
  [...document.querySelectorAll("[data-i18n]")].map((el) => [el.dataset.i18n, el.innerHTML])
);

function updateLocalizedLinks(lang) {
  document.querySelectorAll("a[href]").forEach((link) => {
    const href = link.getAttribute("href");
    if (!href || href.startsWith("#") || href.startsWith("http") || href.startsWith("mailto:") || href.startsWith("tel:")) return;
    if (!href.includes(".html")) return;
    const url = new URL(href, window.location.href);
    url.searchParams.set("lang", lang);
    link.setAttribute("href", `${url.pathname.split("/").pop()}${url.search}${url.hash}`);
  });
}

function applyLanguage(lang) {
  const activeLang = ["de", "es", "en"].includes(lang) ? lang : "de";
  if (typeof window.setLanguage === "function") {
    window.setLanguage(activeLang);
  }
  const dict = activeLang === "de" ? originalText : pageTranslations[activeLang];
  document.documentElement.lang = activeLang;
  localStorage.setItem("gss-language", activeLang);
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const value = dict && dict[el.dataset.i18n];
    if (value) el.innerHTML = value;
  });
  document.querySelectorAll(".lang").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === activeLang);
  });
  updateLocalizedLinks(activeLang); if (typeof window.updatePhoneCountryLabels === "function") window.updatePhoneCountryLabels(); document.querySelectorAll("#contact-form").forEach((form) => { if (typeof window.applyLocalizedValidation === "function") window.applyLocalizedValidation(form); });
}

const requestedLanguage = new URLSearchParams(window.location.search).get("lang");
const savedLanguage = localStorage.getItem("gss-language");
applyLanguage(requestedLanguage || savedLanguage || document.documentElement.lang || "de");

document.querySelectorAll(".lang").forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});












